/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ZhangWanqing (https://sketchfab.com/ZhangWanqing)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cute-alien-68d4df606f73431db8b443e9ee138558
title: cute alien
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.material_10}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.material_9}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.material_8}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.material_7}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.material_6}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.material_6}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.material_5}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.material_4}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.material_4}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.material_4}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.material_4}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.material_4}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.material_3}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.material_2}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials.material_1}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");

// Model Information:
// * title:	cute alien
// * source:	https://sketchfab.com/3d-models/cute-alien-68d4df606f73431db8b443e9ee138558
// * author:	ZhangWanqing (https://sketchfab.com/ZhangWanqing)

// Model License:
// * license type:	CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// * requirements:	Author must be credited. Commercial use is allowed.

// If you use this 3D model in your project be sure to copy paste this credit wherever you share it:
// This work is based on "cute alien" (https://sketchfab.com/3d-models/cute-alien-68d4df606f73431db8b443e9ee138558) by ZhangWanqing (https://sketchfab.com/ZhangWanqing) licensed under CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
